services:
  ai-engine:
    container_name: ai-engine
    hostname: ai-engine
    image: cosmtrek/air
    restart: unless-stopped
    working_dir: /go/src/gomods.euniz.com/gomods/ai-engine
    volumes:
      - .:/go/src/gomods.euniz.com/gomods/ai-engine
    networks:
      - ai-engine-net
    ports:
      - 5180:5000

  ollama:
    container_name: ollama
    hostname: ollama
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ~/.ollama:/root/.ollama
      - /usr/share/ollama/.ollama/models:/usr/share/ollama/.ollama/models
    networks:
      - ai-engine-net
    environment:
      - OLLAMA_MODELS=/usr/share/ollama/.ollama/models

networks:
  ai-engine-net: